name: Run Hello World Script Daily

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at 00:00 UTC
    - cron: '0 6 * * *' # Runs every day at 06:00 UTC
    - cron: '0 12 * * *' # Runs every day at 12:00 UTC
    - cron: '0 18 * * *' # Runs every day at 18:00 UTC

jobs:
  run-batch-script:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run hello_world.bat
        run: |
          .\hello_world.bat
